export const SEND_REQUEST = '[ROOM]SEND_REQUEST';
export const REQUEST_SUCCESS = '[ROOM]REQUEST_SUCCESS';
export const REQUEST_FAILURE = '[ROOM]REQUEST_FAILURE';
export const RESET_ROOM = '[ROOM]RESET_ROOM';