export const SEND_REQUEST = '[ROOMS]SEND_REQUEST'
export const REQUEST_SUCCESS = '[ROOMS]REQUEST_SUCCESS';
export const REQUEST_FAILURE = '[ROOMS]REQUEST_FAILURE';
export const UPDATE_ROOMS = '[ROOMS]UPDATE_ROOMS';